export const user = {
    LOGIN : 'LOGIN',
    SETUSER : 'SETUSER',
    SETEMAILVERIFY : 'SETEMAILVERIFY'
}

export const header = {
    SETLEFT: 'SETHEADERLEFT',
    SETLEFTICON: 'SETHEADERLEFTICON',
    SETRIGHT: 'SETHEADERRIGHT',
    SETRIGHTICON: 'SETHEADERRIGHTICON'
}