export const user = {
    SETLOADING : 'SETAUTHLOADING',
    LOGIN : 'LOGIN',
    SETUSER : 'SETUSER'
}

export const header = {
    SETLEFT: 'SETHEADERLEFT',
    SETLEFTICON: 'SETHEADERLEFTICON',
    SETRIGHT: 'SETHEADERRIGHT',
    SETRIGHTICON: 'SETHEADERRIGHTICON'
}